apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: s3backends.diener.adviser.com
spec:
  conversion:
    strategy: None
  group: diener.adviser.com
  names:
    categories:
    - all
    - diener
    kind: S3Backend
    listKind: S3BackendList
    plural: s3backends
    singular: s3backend
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Configure a s3backend for use with the Diener controller.
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              accessKey:
                description: AccessKey is the AWS access key to use for the S3 bucket.
                type: string
              bucketName:
                description: BucketName is the name of the S3 bucket to use.
                type: string
              endpoint:
                description: Endpoint is the S3 endpoint to use.
                type: string
              maxAgeSeconds:
                description: MaxAge is the maximum age of an object in the cache. 0 means no cache.
                type: number
                default: 3600
              maxObjectSize:
                description: MaxObjectSize is the maximum size of an object to cache.
                type: integer
                default: 100000000
              region:
                description: Region is the AWS region to use for the S3 bucket.
                type: string
              secretKey:
                description: SecretKey is the AWS secret key to use for the S3 bucket.
                type: string
              transferBufSize:
                description: TransferBufSize is the size of the buffer to use when
                  transferring objects from S3 to the cache.
                type: integer
                default: 1048576
            required:
            - accessKey
            - bucketName
            - secretKey
            type: object
          status:
            description: S3Backend defines the observed state of Diener Controller
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: The last time this Condition status changed.
                      format: date-time
                      type: string
                    message:
                      description: Full text reason for current status of the condition.
                      type: string
                    reason:
                      description: One word, camel-case reason for current status
                        of the condition.
                      type: string
                    status:
                      description: True, False, or Unknown
                      type: string
                    type:
                      description: Type indicates the scope of the custom resource
                        status addressed by the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: observedGeneration is the most recent successful generation
                  observed for this CFDTunnel. It corresponds to the CFDTunnel's generation,
                  which is updated on mutation by the API Server.
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
